create table NODO4_CFG.PDD
(
    OBJ_ID NUMBER generated by default as identity
        constraint PK_PDD
            primary key,
    ID_PDD VARCHAR2(35 char) not null,
    ENABLED CHAR(1 char) not null,
    DESCRIZIONE VARCHAR2(35 char) not null,
    IP VARCHAR2(15 char) not null,
    PORTA NUMBER
);

create unique index NODO4_CFG.PK_PDD on NODO4_CFG.PDD (OBJ_ID);
create unique index NODO4_CFG.UQ_PDD on NODO4_CFG.PDD (ID_PDD);

INSERT INTO NODO4_CFG.PDD (OBJ_ID, ID_PDD, ENABLED, DESCRIZIONE, IP, PORTA) VALUES(1, 'localhost', 'Y', 'localhost', '127.0.0.1', NULL);
