create table NODO4_CFG.FTP_SERVERS
(
    OBJ_ID       NUMBER generated by default on null as identity
        constraint PK__FTP_SERV__755589F079FD19BE
            primary key,
    HOST         VARCHAR2(255 char) not null,
    PORT         NUMBER             not null,
    USERNAME     VARCHAR2(35 char)  not null,
    PASSWORD     VARCHAR2(35 char)  not null,
    ROOT_PATH    VARCHAR2(255 char) not null,
    SERVICE      VARCHAR2(255 char) not null,
    TYPE         VARCHAR2(35 char)  not null,
    IN_PATH      VARCHAR2(255 char),
    OUT_PATH     VARCHAR2(255 char),
    HISTORY_PATH VARCHAR2(255 char),
    ENABLED      CHAR
);

insert into NODO4_CFG.FTP_SERVERS (OBJ_ID, HOST, PORT, USERNAME, PASSWORD, ROOT_PATH, SERVICE, TYPE, IN_PATH, OUT_PATH,
                                   HISTORY_PATH, ENABLED)
VALUES (1, 'test.domain', 22, 'username', 'pwdpwdpwd', '/', 'service', 'out', '/in/service', '/out/service',
        '/out/history/service', 'Y');

commit;
