create sequence NODO4_CFG.HIBERNATE_SEQUENCE increment by 1;

-- create tables

create table NODO4_CFG.INTERMEDIARI_PA
(
    OBJ_ID               NUMBER generated by default on null as identity
        constraint PK_INTERMEDIARI_PA
            primary key,
    ID_INTERMEDIARIO_PA  VARCHAR2(35 char)        not null
        constraint UQ_ID_INTERMEDIARIO_PA
        unique,
    ENABLED             CHAR(1 char
) not null,
    CODICE_INTERMEDIARIO VARCHAR2(255 char),
    FAULT_BEAN_ESTESO    CHAR(1 char) default 'N' not null
);

create table NODO4_CFG.QUADRATURE_SCHED
(
    OBJ_ID                NUMBER generated by default on null as identity
        constraint PK_QUADRATURE_SCHED
        primary key,
    ID_SOGGETTO           VARCHAR2(35 char),
    MODALITA              VARCHAR2(35 char),
    TIPO_QUAD             VARCHAR2(35 char),
    DAYS_OF_THE_WEEK_CODE VARCHAR2(7 char),
    JOB_START_DATE        TIMESTAMP(6),
    ENABLED               CHAR,
    ON_CLICK              CHAR,
    JOB_END_HOUR          TIMESTAMP(6),
    JOB_START_HOUR        TIMESTAMP(6),
    TIMESTAMP_LAST_ACTION TIMESTAMP(6),
    TIMESTAMP_END         TIMESTAMP(6),
    TIMESTAMP_BEGIN       TIMESTAMP(6),
    QUAD_LAST_DATE        TIMESTAMP(6),
    TYPE_INIZIO_GIORNATA  CHAR(1 char
) default 'N' not null
);

create table NODO4_CFG.PA
(
    OBJ_ID     NUMBER generated by default on null as identity
        constraint PK_PA
        primary key,
    ID_DOMINIO VARCHAR2(35 char) not null
        constraint UQ_ID_DOMINIO
        unique,
    ENABLED    CHAR(1 char
) not null,
    DESCRIZIONE                       VARCHAR2(70 char),
    RAGIONE_SOCIALE                   VARCHAR2(70 char),
    FK_INT_QUADRATURE                 NUMBER
        constraint FK_PA_INT_QUADRATURE
            references NODO4_CFG.INTERMEDIARI_PA,
    FLAG_REPO_COMMISSIONE_CARICO_PA   CHAR(1 char)      not null,
    EMAIL_REPO_COMMISSIONE_CARICO_PA  VARCHAR2(255 char),
    INDIRIZZO_DOMICILIO_FISCALE       VARCHAR2(255 char),
    CAP_DOMICILIO_FISCALE             CHAR(5),
    SIGLA_PROVINCIA_DOMICILIO_FISCALE VARCHAR2(2 char),
    COMUNE_DOMICILIO_FISCALE          VARCHAR2(255 char),
    DENOMINAZIONE_DOMICILIO_FISCALE   VARCHAR2(255 char),
    PAGAMENTO_PRESSO_PSP              CHAR(1 char)      not null,
    RENDICONTAZIONE_FTP               CHAR(1 char)      not null,
    RENDICONTAZIONE_ZIP               CHAR(1 char)      not null,
    REVOCA_PAGAMENTO                  NUMBER default 0  not null
);

create table NODO4_CFG.STAZIONI
(
    OBJ_ID      NUMBER generated by default on null as identity
        constraint PK_STAZIONI
        primary key,
    ID_STAZIONE VARCHAR2(35 char) not null
        constraint UQ_ID_STAZIONE
        unique,
    ENABLED     CHAR(1 char
) not null,
    IP                    VARCHAR2(100 char),
    NEW_PASSWORD          VARCHAR2(15 char),
    PASSWORD              VARCHAR2(15 char),
    PORTA                 NUMBER                 not null,
    PROTOCOLLO            VARCHAR2(255 char)     not null,
    REDIRECT_IP           VARCHAR2(100 char),
    REDIRECT_PATH         VARCHAR2(100 char),
    REDIRECT_PORTA        NUMBER,
    REDIRECT_QUERY_STRING VARCHAR2(255 char),
    SERVIZIO              VARCHAR2(100 char),
    RT_ENABLED            CHAR(1 char)           not null,
    SERVIZIO_POF          VARCHAR2(100 char),
    FK_INTERMEDIARIO_PA   NUMBER                 not null
        constraint FK_STAZIONI_INTERMEDIARI_PA
            references NODO4_CFG.INTERMEDIARI_PA,
    REDIRECT_PROTOCOLLO   VARCHAR2(35 char),
    PROTOCOLLO_4MOD       VARCHAR2(255 char),
    IP_4MOD               VARCHAR2(100 char),
    PORTA_4MOD            NUMBER,
    SERVIZIO_4MOD         VARCHAR2(255 char),
    PROXY_ENABLED         CHAR(1 char),
    PROXY_HOST            VARCHAR2(100 char),
    PROXY_PORT            NUMBER,
    PROXY_USERNAME        VARCHAR2(15 char),
    PROXY_PASSWORD        VARCHAR2(15 char),
    PROTOCOLLO_AVV        VARCHAR2(255 char),
    IP_AVV                VARCHAR2(100 char),
    PORTA_AVV             NUMBER,
    SERVIZIO_AVV          VARCHAR2(255 char),
    TIMEOUT               NUMBER(19) default 120 not null,
    NUM_THREAD            NUMBER                 not null,
    TIMEOUT_A             NUMBER(19)             not null,
    TIMEOUT_B             NUMBER(19)             not null,
    TIMEOUT_C             NUMBER(19)             not null,
    FLAG_ONLINE           CHAR       default 'Y' not null,
    VERSIONE              NUMBER     default 1.0 not null,
    SERVIZIO_NMP          VARCHAR2(255 char)
);

create table NODO4_CFG.PA_STAZIONE_PA
(
    OBJ_ID         NUMBER generated by default on null as identity
        constraint PK_PA_STAZIONE_PA
        primary key,
    PROGRESSIVO    NUMBER,
    FK_PA          NUMBER not null
        constraint FK_PA_STAZIONE_PA_PA
            references NODO4_CFG.PA,
    FK_STAZIONE    NUMBER not null
        constraint FK_PA_STAZIONE_PA_STAZIONE
            references NODO4_CFG.STAZIONI,
    AUX_DIGIT      NUMBER,
    SEGREGAZIONE   NUMBER,
    QUARTO_MODELLO CHAR(1 char
) not null,
    STAZIONE_NODO  CHAR(1 char) default 'N' not null,
    STAZIONE_AVV   CHAR(1 char) default 'N' not null,
    BROADCAST      CHAR         default 'N' not null
);

-- Insert data

INSERT INTO NODO4_CFG.INTERMEDIARI_PA (OBJ_ID, ID_INTERMEDIARIO_PA, ENABLED, CODICE_INTERMEDIARIO, FAULT_BEAN_ESTESO)
VALUES (2, '80007580279', 'Y', 'Regione Veneto', 'N');

INSERT INTO NODO4_CFG.QUADRATURE_SCHED (OBJ_ID, ID_SOGGETTO, MODALITA, TIPO_QUAD, DAYS_OF_THE_WEEK_CODE, JOB_START_DATE,
                                        ENABLED, ON_CLICK, JOB_END_HOUR, JOB_START_HOUR, TIMESTAMP_LAST_ACTION,
                                        TIMESTAMP_END, TIMESTAMP_BEGIN, QUAD_LAST_DATE, TYPE_INIZIO_GIORNATA)
VALUES (1, 'INTERMEDIARIOPAP', 'GIORNALIERA', 'INT_PA', 'FTTTTTF',
        TO_TIMESTAMP('2013-10-17 00:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), 'N', 'N',
        TO_TIMESTAMP('2013-10-24 08:00:35.833000', 'YYYY-MM-DD HH24:MI:SS.FF6'),
        TO_TIMESTAMP('2013-10-24 07:00:35.833000', 'YYYY-MM-DD HH24:MI:SS.FF6'),
        TO_TIMESTAMP('2013-12-11 07:00:56.627000', 'YYYY-MM-DD HH24:MI:SS.FF6'),
        TO_TIMESTAMP('2013-12-11 07:00:56.627000', 'YYYY-MM-DD HH24:MI:SS.FF6'),
        TO_TIMESTAMP('2013-12-11 07:00:56.487000', 'YYYY-MM-DD HH24:MI:SS.FF6'),
        TO_TIMESTAMP('2013-12-11 00:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), 'Y');

INSERT INTO NODO4_CFG.PA (OBJ_ID, ID_DOMINIO, ENABLED, DESCRIZIONE, RAGIONE_SOCIALE, FK_INT_QUADRATURE,
                          FLAG_REPO_COMMISSIONE_CARICO_PA, EMAIL_REPO_COMMISSIONE_CARICO_PA,
                          INDIRIZZO_DOMICILIO_FISCALE, CAP_DOMICILIO_FISCALE, SIGLA_PROVINCIA_DOMICILIO_FISCALE,
                          COMUNE_DOMICILIO_FISCALE, DENOMINAZIONE_DOMICILIO_FISCALE, PAGAMENTO_PRESSO_PSP,
                          RENDICONTAZIONE_FTP, RENDICONTAZIONE_ZIP, REVOCA_PAGAMENTO)
VALUES (190, '00168480242', 'Y', 'Comune di Bassano del Grappa', 'Comune di Bassano del Grappa', null, 'N', null, null,
        null, null, null, null, 'Y', 'N', 'N', 0);

INSERT INTO NODO4_CFG.STAZIONI (OBJ_ID, ID_STAZIONE, ENABLED, IP, NEW_PASSWORD, PASSWORD, PORTA, PROTOCOLLO,
                                REDIRECT_IP, REDIRECT_PATH, REDIRECT_PORTA, REDIRECT_QUERY_STRING, SERVIZIO, RT_ENABLED,
                                SERVIZIO_POF, FK_INTERMEDIARIO_PA, REDIRECT_PROTOCOLLO, PROTOCOLLO_4MOD, IP_4MOD,
                                PORTA_4MOD, SERVIZIO_4MOD, PROXY_ENABLED, PROXY_HOST, PROXY_PORT, PROXY_USERNAME,
                                PROXY_PASSWORD, PROTOCOLLO_AVV, IP_AVV, PORTA_AVV, SERVIZIO_AVV, TIMEOUT, NUM_THREAD,
                                TIMEOUT_A, TIMEOUT_B, TIMEOUT_C, FLAG_ONLINE, VERSIONE, SERVIZIO_NMP)
VALUES (2, '80007580279_01', 'Y', 'NodoDeiPagamentiDellaPATest.sia.eu', null, 'password', 80, 'HTTP',
        'paygov.collaudo.regione.veneto.it', 'nodo-regionale-fesp/paaInviaRispostaPagamento.html', 443, null,
        'openspcoop/PD/RT6TPDREGVENETO', 'Y', 'openspcoop/PD/CCP6TPDREGVENETO', 2, 'HTTPS', 'HTTP', null, null, null,
        'Y', '10.101.1.95', 8080, null, null, 'HTTP', null, null, null, 120, 2, 15, 30, 120, 'Y', 1, null);

INSERT INTO NODO4_CFG.PA_STAZIONE_PA (OBJ_ID, PROGRESSIVO, FK_PA, FK_STAZIONE, AUX_DIGIT, SEGREGAZIONE, QUARTO_MODELLO,
                                      STAZIONE_NODO, STAZIONE_AVV, BROADCAST)
VALUES (430, 1, 190, 2, null, 1, 'N', 'Y', 'N', 'N');

INSERT INTO NODO4_CFG.PA (OBJ_ID, ID_DOMINIO, ENABLED, DESCRIZIONE, RAGIONE_SOCIALE, FK_INT_QUADRATURE,
                          FLAG_REPO_COMMISSIONE_CARICO_PA, EMAIL_REPO_COMMISSIONE_CARICO_PA,
                          INDIRIZZO_DOMICILIO_FISCALE, CAP_DOMICILIO_FISCALE, SIGLA_PROVINCIA_DOMICILIO_FISCALE,
                          COMUNE_DOMICILIO_FISCALE, DENOMINAZIONE_DOMICILIO_FISCALE, PAGAMENTO_PRESSO_PSP,
                          RENDICONTAZIONE_FTP, RENDICONTAZIONE_ZIP, REVOCA_PAGAMENTO)
VALUES (191, '1110001', 'Y', 'Comune di Roma', 'Comune di Roma', null, 'N', null, null,
        null, null, null, null, 'Y', 'N', 'N', 0);

COMMIT;
