create table NODO4_CFG.INFORMATIVE_PA_MASTER
(
    OBJ_ID               NUMBER generated by default on null as identity
        constraint PK_INFORMATIVE_PA_MASTER
        primary key,
    ID_INFORMATIVA_PA    VARCHAR2(35 char) not null,
    DATA_INIZIO_VALIDITA TIMESTAMP(6),
    DATA_PUBBLICAZIONE   TIMESTAMP(6),
    FK_PA                NUMBER            not null
        constraint FK_INFORMATIVE_PA_MASTER_PA
            references NODO4_CFG.PA,
    FK_BINARY_FILE       NUMBER
        constraint FK_INFORMATIVE_PA_MASTER_BINARY_FILE
            references NODO4_CFG.BINARY_FILE,
    VERSIONE             VARCHAR2(35 char),
    PAGAMENTI_PRESSO_PSP NUMBER,
    constraint UQ_INFORMATIVA_PA
        unique (FK_PA, ID_INFORMATIVA_PA)
);

create table NODO4_CFG.INFORMATIVE_PA_DETAIL
(
    OBJ_ID                   NUMBER generated as identity
        constraint PK_INFORMATIVE_PA_DETAIL
            primary key,
    FLAG_DISPONIBILITA       CHAR(1 char) not null,
    GIORNO                   VARCHAR2(35 char),
    TIPO                     VARCHAR2(35 char),
    FK_INFORMATIVA_PA_MASTER NUMBER       not null
        constraint FK_INFORMATIVE_PA_MASTER
            references NODO4_CFG.INFORMATIVE_PA_MASTER
);

create table NODO4_CFG.INFORMATIVE_PA_FASCE
(
    OBJ_ID                   NUMBER generated as identity
        constraint PK_INFORMATIVE_PA_FASCE
            primary key,
    ORA_A                    VARCHAR2(35 char),
    ORA_DA                   VARCHAR2(35 char),
    FK_INFORMATIVA_PA_DETAIL NUMBER not null
        constraint FK_INFORMATIVE_PA_DETAIL
            references NODO4_CFG.INFORMATIVE_PA_DETAIL
);

INSERT INTO NODO4_CFG.INFORMATIVE_PA_MASTER (OBJ_ID, ID_INFORMATIVA_PA, DATA_INIZIO_VALIDITA, DATA_PUBBLICAZIONE, FK_PA,
                                             FK_BINARY_FILE, VERSIONE, PAGAMENTI_PRESSO_PSP)
VALUES (1, '1', TO_TIMESTAMP('2014-08-07 12:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'),
        TO_TIMESTAMP('2014-08-06 12:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), 190, 201, null, 0);

COMMIT;
