create table NODO4_CFG.WFESP_PLUGIN_CONF
(
    OBJ_ID                   NUMBER generated by default on null as identity
        constraint PK_WFESP_PLUGIN_CONF
            primary key,
    ID_SERV_PLUGIN           VARCHAR2(35 char) not null
        constraint UQ_ID_SERV_PLUGIN
            unique,
    PROFILO_PAG_CONST_STRING VARCHAR2(150 char),
    PROFILO_PAG_SOAP_RULE    VARCHAR2(150 char),
    PROFILO_PAG_RPT_XPATH    VARCHAR2(150 char),
    ID_BEAN                  VARCHAR2(255 char)
);


create table NODO4_CFG.CANALI_NODO
(
    OBJ_ID                NUMBER generated by default on null as identity
        constraint PK_CANALI_NODO
            primary key,
    REDIRECT_IP           VARCHAR2(100 char),
    REDIRECT_PATH         VARCHAR2(100 char),
    REDIRECT_PORTA        NUMBER,
    REDIRECT_QUERY_STRING VARCHAR2(255 char),
    MODELLO_PAGAMENTO     VARCHAR2(255 char)       not null,
    MULTI_PAYMENT         CHAR(1 char)             not null,
    RAGIONE_SOCIALE       VARCHAR2(35 char),
    RPT_RT_COMPLIANT      CHAR(1 char)             not null,
    WSAPI                 VARCHAR2(15 char),
    REDIRECT_PROTOCOLLO   VARCHAR2(35 char),
    ID_SERV_PLUGIN        VARCHAR2(35 char)
        constraint FK_CANALI_SERV_PLUGIN
            references NODO4_CFG.WFESP_PLUGIN_CONF (ID_SERV_PLUGIN),
    ID_CLUSTER            VARCHAR2(255 char),
    ID_FESP_INSTANCE      VARCHAR2(275 char),
    LENTO                 CHAR(1 char)             not null,
    RT_PUSH               CHAR(1 char)             not null,
    AGID_CHANNEL          CHAR(1 char)             not null,
    ON_US                 CHAR(1 char)             not null,
    CARRELLO_CARTE        CHAR(1 char)             not null,
    RECOVERY              CHAR(1 char) default 'N' not null,
    MARCA_BOLLO_DIGITALE  CHAR                     not null,
    FLAG_IO               CHAR         default 'N'
);


create table NODO4_CFG.CANALI
(
    OBJ_ID               NUMBER generated by default on null as identity
        constraint PK_CANALI
            primary key,
    ID_CANALE            VARCHAR2(35 char)        not null
        constraint UQ_ID_CANALE
            unique,
    ENABLED              CHAR(1 char)             not null,
    IP                   VARCHAR2(100 char),
    NEW_PASSWORD         VARCHAR2(15 char),
    PASSWORD             VARCHAR2(15 char),
    PORTA                NUMBER                   not null,
    PROTOCOLLO           VARCHAR2(255 char)       not null,
    SERVIZIO             VARCHAR2(100 char),
    DESCRIZIONE          VARCHAR2(70 char),
    FK_INTERMEDIARIO_PSP NUMBER                   not null
        constraint FK_CANALI_INTERMEDIARI_PSP
            references NODO4_CFG.INTERMEDIARI_PSP,
    PROXY_ENABLED        CHAR(1 char)             not null,
    PROXY_HOST           VARCHAR2(100 char),
    PROXY_PASSWORD       VARCHAR2(15 char),
    PROXY_PORT           NUMBER,
    PROXY_USERNAME       VARCHAR2(15 char),
    CANALE_NODO          CHAR(1 char) default 'N' not null,
    CANALE_AVV           CHAR(1 char) default 'N' not null,
    FK_CANALI_NODO       NUMBER
        constraint FK_CANALI_NODO
            references NODO4_CFG.CANALI_NODO,
    TIMEOUT              NUMBER       default 120 not null,
    NUM_THREAD           NUMBER                   not null,
    USE_NEW_FAULT_CODE   CHAR                     not null,
    TIMEOUT_A            NUMBER(19)               not null,
    TIMEOUT_B            NUMBER(19)               not null,
    TIMEOUT_C            NUMBER(19)               not null,
    SERVIZIO_NMP         VARCHAR2(255 char)
);


INSERT INTO NODO4_CFG.WFESP_PLUGIN_CONF (OBJ_ID, ID_SERV_PLUGIN, PROFILO_PAG_CONST_STRING, PROFILO_PAG_SOAP_RULE, PROFILO_PAG_RPT_XPATH, ID_BEAN) VALUES (1, 'idPsp1', null, 'profilo=$identificativoIntermediarioPA$~$identificativoStazioneIntermediarioPA$', null, 'defaultForwardProcessor');
INSERT INTO NODO4_CFG.CANALI_NODO (OBJ_ID, REDIRECT_IP, REDIRECT_PATH, REDIRECT_PORTA, REDIRECT_QUERY_STRING, MODELLO_PAGAMENTO, MULTI_PAYMENT, RAGIONE_SOCIALE, RPT_RT_COMPLIANT, WSAPI, REDIRECT_PROTOCOLLO, ID_SERV_PLUGIN, ID_CLUSTER, ID_FESP_INSTANCE, LENTO, RT_PUSH, AGID_CHANNEL, ON_US, CARRELLO_CARTE, RECOVERY, MARCA_BOLLO_DIGITALE, FLAG_IO) VALUES (1, null, null, null, null, 'ATTIVATO_PRESSO_PSP', 'N', null, 'N', null, 'HTTP', null, 'CL_1', null, 'N', 'Y', 'N', 'N', 'N', 'Y', 'N', 'N');
INSERT INTO NODO4_CFG.CANALI (OBJ_ID, ID_CANALE, ENABLED, IP, NEW_PASSWORD, PASSWORD, PORTA, PROTOCOLLO, SERVIZIO, DESCRIZIONE, FK_INTERMEDIARIO_PSP, PROXY_ENABLED, PROXY_HOST, PROXY_PASSWORD, PROXY_PORT, PROXY_USERNAME, CANALE_NODO, CANALE_AVV, FK_CANALI_NODO, TIMEOUT, NUM_THREAD, USE_NEW_FAULT_CODE, TIMEOUT_A, TIMEOUT_B, TIMEOUT_C, SERVIZIO_NMP) VALUES (1, '00001060966_01', 'Y', '1.1.1.1', null, 'FakePay', 443, 'HTTPS', 'basepath/services/fake', null, 6, 'Y', '2.2.2.2', null, 8080, null, 'Y', 'N', 1, 120, 2, 'Y', 15, 30, 120, null);

commit;
