create table NODO4_CFG.ELENCO_SERVIZI
(
    OBJ_ID             NUMBER generated by default on null as identity
        constraint PK_ELENCO_SERVIZI
            primary key,
    PSP_ID             VARCHAR2(35 char),
    FLUSSO_ID          VARCHAR2(35 char),
    PSP_RAG_SOC        VARCHAR2(255 char),
    PSP_FLAG_STORNO    CHAR,
    PSP_FLAG_BOLLO     CHAR,
    INTM_ID            VARCHAR2(35 char),
    CANALE_ID          VARCHAR2(35 char),
    NOME_SERVIZIO      VARCHAR2(35 char),
    CANALE_MOD_PAG     NUMBER,
    TIPO_VERS_COD      VARCHAR2(255 char),
    CODICE_LINGUA      CHAR(2),
    INF_COND_EC_MAX    VARCHAR2(35 char),
    INF_DESC_SERV      VARCHAR2(511 char),
    INF_DISP_SERV      VARCHAR2(511 char),
    INF_URL_CANALE     VARCHAR2(255 char),
    IMPORTO_MINIMO     FLOAT,
    IMPORTO_MASSIMO    FLOAT,
    COSTO_FISSO        FLOAT,
    TIMESTAMP_INS      TIMESTAMP(6),
    DATA_VALIDITA      TIMESTAMP(6),
    LOGO_PSP           BLOB,
    TAGS               VARCHAR2(135 char),
    LOGO_SERVIZIO      BLOB,
    CANALE_APP         CHAR,
    ON_US              CHAR,
    CARRELLO_CARTE     CHAR,
    CODICE_ABI         VARCHAR2(5 char),
    CODICE_MYBANK      VARCHAR2(35 char),
    CODICE_CONVENZIONE VARCHAR2(35 char),
    FLAG_IO            CHAR
);

INSERT INTO NODO4_CFG.ELENCO_SERVIZI (OBJ_ID, PSP_ID, FLUSSO_ID, PSP_RAG_SOC, PSP_FLAG_STORNO, PSP_FLAG_BOLLO, INTM_ID, CANALE_ID, NOME_SERVIZIO, CANALE_MOD_PAG, TIPO_VERS_COD, CODICE_LINGUA, INF_COND_EC_MAX, INF_DESC_SERV, INF_DISP_SERV, INF_URL_CANALE, IMPORTO_MINIMO, IMPORTO_MASSIMO, COSTO_FISSO, TIMESTAMP_INS, DATA_VALIDITA, LOGO_PSP, TAGS, LOGO_SERVIZIO, CANALE_APP, ON_US, CARRELLO_CARTE, CODICE_ABI, CODICE_MYBANK, CODICE_CONVENZIONE, FLAG_IO) VALUES (1, 'BPPIITRRZZZ', 'WISP_1_1_20210101', 'Cassa di Risparmio di Parma e Piacenza S.p.A.', 'N', 'N', '02113530345', '00001060966_01', 'non comunicato', 0, 'CP', 'IT', null, 'Il servizio consente ai clienti di effettuare pagamenti elettronici online verso la Pubblica Amministrazione e i gestori di serviz', '24/7', null, 0, 99999999.99, 1.99, TO_TIMESTAMP('2021-12-10 00:05:09.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), TO_TIMESTAMP('2017-07-12 00:02:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), '16', 'Diners;V-Pay', '16', 'N', 'N', 'N', 'TBD', null, null, 'N');

commit;
