create table NODO4_CFG.CDI_MASTER
(
    OBJ_ID               NUMBER generated by default on null as identity
        constraint PK_CDI_MASTER
            primary key,
    ID_INFORMATIVA_PSP   VARCHAR2(35 char) not null,
    DATA_INIZIO_VALIDITA TIMESTAMP(6),
    DATA_PUBBLICAZIONE   TIMESTAMP(6),
    LOGO_PSP             BLOB,
    URL_INFORMAZIONI_PSP VARCHAR2(255 char),
    MARCA_BOLLO_DIGITALE NUMBER            not null,
    STORNO_PAGAMENTO     NUMBER            not null,
    FK_PSP               NUMBER            not null
        constraint FK_CDI_MASTER_TO_PSP
            references NODO4_CFG.PSP,
    FK_BINARY_FILE       NUMBER            not null
        constraint FK_CDI_MASTER_TO_BINARY_FILE
            references NODO4_CFG.BINARY_FILE,
    VERSIONE             VARCHAR2(35 char),
    constraint UQ_INFORMATIVA_CDI
        unique (FK_PSP, ID_INFORMATIVA_PSP)
);

INSERT INTO NODO4_CFG.CDI_MASTER (OBJ_ID, ID_INFORMATIVA_PSP, DATA_INIZIO_VALIDITA, DATA_PUBBLICAZIONE, LOGO_PSP, URL_INFORMAZIONI_PSP, MARCA_BOLLO_DIGITALE, STORNO_PAGAMENTO, FK_PSP, FK_BINARY_FILE, VERSIONE)
VALUES (3, 'WISP_1_2_20211229', TO_TIMESTAMP('2017-05-16 00:02:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), TO_TIMESTAMP('2017-05-16 00:01:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), '16', 'http://host/service', 0, 0, 1, 201, null);

commit;
