create table NODO4_CFG.CDI_MASTER
(
    OBJ_ID               NUMBER generated by default on null as identity
        constraint PK_CDI_MASTER
            primary key,
    ID_INFORMATIVA_PSP   VARCHAR2(35 char) not null,
    DATA_INIZIO_VALIDITA TIMESTAMP(6),
    DATA_PUBBLICAZIONE   TIMESTAMP(6),
    LOGO_PSP             BLOB,
    URL_INFORMAZIONI_PSP VARCHAR2(255 char),
    MARCA_BOLLO_DIGITALE NUMBER            not null,
    STORNO_PAGAMENTO     NUMBER            not null,
    FK_PSP               NUMBER            not null
        constraint FK_CDI_MASTER_TO_PSP
            references NODO4_CFG.PSP,
    FK_BINARY_FILE       NUMBER            not null
        constraint FK_CDI_MASTER_TO_BINARY_FILE
            references NODO4_CFG.BINARY_FILE,
    VERSIONE             VARCHAR2(35 char),
    constraint UQ_INFORMATIVA_CDI
        unique (FK_PSP, ID_INFORMATIVA_PSP)
);

create table NODO4_CFG.CDI_DETAIL
(
    OBJ_ID                        NUMBER generated by default on null as identity
        constraint PK_CDI_DETAIL
            primary key,
    NOME_SERVIZIO                 VARCHAR2(35 char) not null,
    PRIORITA                      NUMBER            not null,
    MODELLO_PAGAMENTO             NUMBER            not null,
    FK_CDI_MASTER                 NUMBER            not null
        constraint FK_CDI_DETAIL_TO_CDI_MASTER
            references NODO4_CFG.CDI_MASTER,
    FK_PSP_CANALE_TIPO_VERSAMENTO NUMBER            not null
        constraint FK_CDI_DETAIL_TO_PSP_CANALE_TIPO_VERSAMENTO
            references NODO4_CFG.PSP_CANALE_TIPO_VERSAMENTO,
    CANALE_APP                    NUMBER,
    TAGS                          VARCHAR2(135 char),
    LOGO_SERVIZIO                 BLOB
);

create table NODO4_CFG.CDI_FASCIA_COSTO_SERVIZIO
(
    OBJ_ID             NUMBER generated by default on null as identity
        constraint PK_CDI_FASCIA_COSTO_SERVIZIO
            primary key,
    IMPORTO_MINIMO     FLOAT  not null,
    IMPORTO_MASSIMO    FLOAT  not null,
    COSTO_FISSO        FLOAT  not null,
    FK_CDI_DETAIL      NUMBER not null
        constraint FK_CDI_FASCIA_COSTO_SERVIZIO_TO_CDI_DETAIL
            references NODO4_CFG.CDI_DETAIL,
    VALORE_COMMISSIONE FLOAT,
    CODICE_CONVENZIONE VARCHAR2(35 char)
);

create table NODO4_CFG.CDI_INFORMAZIONI_SERVIZIO
(
    OBJ_ID                  NUMBER generated by default on null as identity
        constraint PK_CDI_INFORMAZIONI_SERVIZIO
            primary key,
    CODICE_LINGUA           CHAR(2 char)       not null,
    DESCRIZIONE_SERVIZIO    VARCHAR2(140 char) not null,
    DISPONIBILITA_SERVIZIO  VARCHAR2(140 char) not null,
    URL_INFORMAZIONI_CANALE VARCHAR2(255 char),
    FK_CDI_DETAIL           NUMBER             not null
        constraint FK_CDI_INFORMAZIONI_SERVIZIO_TO_CDI_DETAIL
            references NODO4_CFG.CDI_DETAIL,
    LIMITAZIONI_SERVIZIO    VARCHAR2(140 char)
);

create table NODO4_CFG.CDI_PREFERENCES
(
    OBJ_ID                NUMBER generated by default on null as identity
        constraint PK__CDI_PREF__755589F03429BB53
            primary key,
    FK_INFORMATIVA_DETAIL NUMBER             not null
        constraint FK_INFORMATIVA_DETAIL_TO_CDI_DETAIL
            references NODO4_CFG.CDI_DETAIL,
    SELLER                VARCHAR2(255 char) not null,
    BUYER                 VARCHAR2(255 char),
    COSTO_CONVENZIONE     NUMBER             not null
);


INSERT INTO NODO4_CFG.CDI_MASTER (OBJ_ID, ID_INFORMATIVA_PSP, DATA_INIZIO_VALIDITA, DATA_PUBBLICAZIONE, LOGO_PSP,
                                  URL_INFORMAZIONI_PSP, MARCA_BOLLO_DIGITALE, STORNO_PAGAMENTO, FK_PSP, FK_BINARY_FILE,
                                  VERSIONE)
VALUES (3, 'WISP_1_2_20211229', TO_TIMESTAMP('2017-05-16 00:02:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'),
        TO_TIMESTAMP('2017-05-16 00:01:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), '16', 'http://host/service', 0, 0, 1,
        201, null);

commit;
