#!/bin/bash

DB_HOST_IPADDRESS=$1
DB_HOST_PORT=$2
DB_HOST_NAME=$3
DB_USERNAME=$4
DB_PASSWORD=$5
DB_DRIVER_PATH=$6

python3 deleteAll.py DB_HOST_IPADDRESS DB_HOST_PORT DB_HOST_NAME DB_USERNAME DB_PASSWORD DB_DRIVER_PATH

echo "Deleted all record in tables IBAN and IBAN_MASTER"



