apiVersion: v2
name: core
description: APIs to manage configuration for CI and PSP of pagoPA
type: application
version: 0.197.0
appVersion: 0.59.29
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: postgresql
    condition: postgresql.enabled
# - name: microservice-chart
#   version: 2.8.0
#   repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
#   alias: oracle
#   condition: oracle.enabled
