apiVersion: v2
name: pagopa-api-config
description: APIs to manage configuration for CI and PSP of the Nodo dei Pagamenti
type: application
version: 1.0.0
appVersion: 0.29.1-28-aks
dependencies:
  - name: microservice-chart
    version: 2.8.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
