apiVersion: v2
name: core
description: APIs to manage configuration for CI and PSP of pagoPA
type: application
version: 0.37.23
appVersion: 0.37.1-1-fix-aks-oracle
dependencies:
  - name: microservice-chart
    version: 2.8.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: postgresql
    condition: postgresql.enabled
  - name: microservice-chart
    version: 2.8.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: oracle
    condition: oracle.enabled
