apiVersion: v2
name: core
description: APIs to manage configuration for CI and PSP of pagoPA
type: application
version: 0.157.0
appVersion: 0.59.3-1-PAGOPA-1732-flags-aca-standin-ciStation
dependencies:
  - name: microservice-chart
    version: 2.8.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: postgresql
    condition: postgresql.enabled
  - name: microservice-chart
    version: 2.8.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: oracle
    condition: oracle.enabled
