apiVersion: v2
name: core
description: APIs to manage configuration for CI and PSP of pagoPA
type: application
version: 0.198.0
appVersion: 0.59.30
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: postgresql
    condition: postgresql.enabled
# - name: microservice-chart
#   version: 2.8.0
#   repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
#   alias: oracle
#   condition: oracle.enabled
