apiVersion: v2
name: core
description: APIs to manage configuration for CI and PSP of pagoPA
type: application
version: 0.145.0
appVersion: 0.58.23-1-PAGOPA-1770-api-cfg-issue-paginazioni-canali-e-stazioni
dependencies:
  - name: microservice-chart
    version: 2.8.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: postgresql
    condition: postgresql.enabled
  - name: microservice-chart
    version: 2.8.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: oracle
    condition: oracle.enabled
