name: Integration Tests

on:
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Select the Environment
        options:
          - dev
          - uat
          - prod


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Dump GitHub context
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}

      - name: Run Integration Tests
        run: |
          cd ./integration-test
          sh run_integration_test.sh ${{ ( inputs.environment != null && inputs.environment) || 'dev'  }}
