name: Self Hosted Runner

on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: The name of the environment where to deploy
        type: string
      env_short:
        required: true
        description: The short name of the environment (d, u or p)
        type: string
      matrix:
        required: true
        description: The environment of the job
        type: string
      beta:
        required: false
        type: boolean
        description: deploy beta version on AKS
        default: false
    secrets:
      token:
        required: true
        description: Github Token

env:
  NAMESPACE: apiconfig
  APP_NAME: pagopaapiconfig


permissions:
  id-token: write
  contents: read

jobs:
  create_runner:
    name: Create Runner
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    if: ${{ inputs.matrix == inputs.environment || inputs.environment == 'all' }}
    outputs:
      runner_name: ${{ steps.create_github_runner.outputs.runner_name }}
    steps:
      - name: Create GitHub Runner
        id: create_github_runner
        # from https://github.com/pagopa/github-self-hosted-runner-azure-create-action/commits/main
        uses: pagopa/github-self-hosted-runner-azure-create-action@b4590e069e753daee6bc9809d484523cc7026035
        with:
          client_id: ${{ vars.client_id }}
          tenant_id: ${{ vars.tenant_id }}
          subscription_id: ${{ vars.subscription_id }}
          container_app_environment_name: pagopa-${{ inputs.env_short }}-github-runner-cae
          resource_group_name: pagopa-${{ inputs.env_short }}-github-runner-rg
          pat_token: ${{ inputs.token }}

  deploy:
    needs: [ create_runner ]
    runs-on: [ self-hosted, "${{ needs.create_runner.outputs.runner_name }}" ]
    if: ${{ inputs.matrix == inputs.environment || inputs.environment == 'all' }}
    name: Deploy on AKS
    steps:
      - name: Deploy
        uses: pagopa/github-actions-template/aks-deploy@main
        with:
          branch: ${{ github.ref_name }}
          client_id: ${{ inputs.client_id }}
          tenant_id: ${{ inputs.tenant_id }}
          subscription_id: ${{ inputs.subscription_id }}
          env: ${{ inputs.env }}
          namespace: ${{ env.NAMESPACE }}
          cluster_name: pagopa-${{ inputs.env_short }}-weu-${{ inputs.environment }}-aks
          resource_group: pagopa-${{ inputs.env_short }}-weu-${{ inputs.environment }}-aks-rg
          app_name: ${{ env.APP_NAME }}
          helm_upgrade_options: ${{( inputs.beta && '--set microservice-chart.deployment.create=false') || '' }}

  cleanup_runner:
    name: Cleanup Runner
    if: always()
    runs-on: ubuntu-22.04
    environment: dev-runner
    needs: [ create_runner, deploy ]
    steps:
      - name: Cleanup GitHub Runner
        id: cleanup_github_runner
        # from https://github.com/pagopa/github-self-hosted-runner-azure-cleanup-action/commits/main
        uses: pagopa/github-self-hosted-runner-azure-cleanup-action@97731a35e6ffc79b66c4dfd2aae5e4fd04e3ebb5
        with:
          client_id: ${{ vars.client_id }}
          tenant_id: ${{ vars.tenant_id }}
          subscription_id: ${{ vars.subscription_id }}
          resource_group_name: pagopa-${{ inputs.env_short }}-github-runner-rg
          runner_name: ${{ needs.create_runner.outputs.runner_name }}
          pat_token: ${{ inputs.token }}
